# Generated by Django 4.2.2 on 2023-06-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0005_alter_post_post_image'),
        ('user_api', '0002_rename_profile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='posts',
            field=models.ManyToManyField(to='blog_api.post'),
        ),
    ]
