# Generated by Django 4.2.2 on 2023-06-12 08:58

import blog_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('leagues', 'Leagues'), ('players highlights', 'Players highlights'), ('latest news', 'Latest News'), ('videos', 'Videos')], default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(default='default_video.mp4', upload_to='videos/', validators=[blog_api.models.validate_video_file]),
        ),
    ]
