# Generated by Django 4.2.2 on 2023-06-12 09:16

import blog_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_post_category_post_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='post_image_pics', validators=[blog_api.models.validate_image_format]),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, default='default_video.mp4', null=True, upload_to='videos/', validators=[blog_api.models.validate_video_file]),
        ),
    ]
