# Generated by Django 4.2.2 on 2023-06-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0004_alter_post_post_image_alter_post_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='post_image_pics'),
        ),
    ]
